# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('login_key', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(default='None', max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=16, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('answer', models.CharField(max_length=50, verbose_name='Question')),
                ('head_picture_address', models.CharField(default='', max_length=200)),
                ('permission_group', models.IntegerField(default=0, verbose_name='Permission Group')),
                ('sign_up_time', models.TimeField(auto_now=True)),
                ('last_login_time', models.TimeField(auto_now_add=True)),
                ('sign_up_ip', models.GenericIPAddressField()),
                ('last_login_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.User')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'female')], null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('profile', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.QuestionList'),
        ),
    ]
