# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('GID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
    ]
