# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('GID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.User')),
                ('permission', models.CharField(max_length=200)),
            ],
        ),
    ]
