# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.User')),
                ('permission', models.CharField(max_length=200)),
            ],
        ),
    ]
